### ISSUE TITLE
Y.npy and X.npy are missed ?

### ISSUE THREAD

**Issue by MhmudAlpurd** [manankshastri/Trigger-Word-Detection#1]
Hi @manankshastri, thanks for this repository. When I run the project, I find the error: X.npy, Y.npy, X_dev.npy, and Y_dev.npy are missed. I couldn't find them in the repository. How or where can I download them?

Best wishes. 
Mahmoud

**Comment by manankshastri** [comment]
https://drive.google.com/drive/folders/1LQ972nN98WiPK1dQRD1qGjpIMg7eoSTo?usp=sharing
